Feature 11 create update items
Metatavu/odata-mock pull request #12
Opened 2022-03-21 13:18 UTC by platonovsimeon

Resolves #11

2022-03-21 18:46 UTC, anttileppa requested changes

2022-03-21 18:46 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/odata/mock/data/DataProvider.kt
> +     * Reads entity by entry id
It seems to return entity, not entry

2022-03-21 18:46 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/odata/mock/processor/ODataProcessor.kt
> +        }
```suggestion
        val entryData = String(request.body.readAllBytes())
        val edmEntitySet = getEdmEntitySet(uriInfo.asUriInfoResource())
        val idPropertyName = edmEntitySet.entityType.keyPropertyRefs.first().name
        val idPropertyValue = jacksonObjectMapper().readTree(entryData).get(idPropertyName)
        val entityName = edmEntitySet.entityType.name
        val entryIds = mutableListOf<UUID>()

        DataContainer.getEntries(entityName).forEach {
            val mockEntryId = it.id!!
            val foundEntity = DataProvider().readByEntryId(edmEntitySet, mockEntryId)!!
            val entryId = "${foundEntity.getProperty(idPropertyName).value}"
            val queryId = "$idPropertyValue".trim('"')

            if (entryId == queryId) {
                DataContainer.removeEntry(mockEntryId)
                entryIds.add(mockEntryId)
            }
        }

        if (entryIds.size == 0) {
            throw ODataApplicationException(
                "No entry found for this key", HttpStatusCode.NOT_FOUND
                    .statusCode, Locale.ENGLISH
            )
        } else {
            val serializedContent = createSerializedEntity(
                entry = Entry(id = entryIds.first(), name = entityName, data = entryData),
                entitySet = edmEntitySet,
                responseFormat = responseFormat,
                uriInfo = uriInfo
            ).content
            response.content = serializedContent
            response.statusCode = HttpStatusCode.OK.statusCode
            response.setHeader(HttpHeader.CONTENT_TYPE, responseFormat.toContentTypeString())
        }
```

2022-03-21 18:46 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/odata/mock/processor/ODataProcessor.kt
> +        response.content = serializedContent
```suggestion
        DataContainer.addEntry(Entry(name = entryName, data = entryData))
        response.content = entryData.byteInputStream()
```

2022-03-21 18:46 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/odata/mock/processor/ODataProcessor.kt
> +            response.content = serializedContent
```suggestion
            DataContainer.addEntry(Entry(id = entryIds.first(), name = entityName, data = entryData))
            response.content = entryData.byteInputStream()
```

2022-03-21 18:46 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/odata/mock/processor/ODataProcessor.kt
> +        if (entries.size == 0) {
```suggestion
        if (entryIds.size == 0) {
```

2022-03-21 18:46 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/odata/mock/processor/ODataProcessor.kt
> +        }
```suggestion
        val entryIds = mutableListOf<UUID>()

        DataContainer.getEntries(entityName).forEach {
            val mockEntryId = it.id!!
            val foundEntity = DataProvider().readByEntryId(edmEntitySet, mockEntryId)!!
            val entryId = "${foundEntity.getProperty(idPropertyName).value}"
            val queryId = "$idPropertyValue".trim('"')

            if (entryId == queryId) {
                DataContainer.removeEntry(mockEntryId)
                entryIds.add(mockEntryId)
            }
        }
```

2022-03-22 11:44 UTC, platonovsimeon commented on src/main/kotlin/fi/metatavu/odata/mock/data/DataProvider.kt
> +     * Reads entity by entry id
Fixed

2022-03-22 12:16 UTC, merged